### ISSUE TITLE
Spelling error?

### ISSUE THREAD

**Issue by ceterumnet** [leecalcote/talks#1]
If you look at the slide here:
http://calcotestudios.com/ccco#/5/9

You mention "traefic" - is this supposed to be "traefik?"

Also you mention "Marathon offers two TCP/HTTP proxy" should that be "Marathon offers two TCP/HTTP proxies?"

Great presentation btw.

**Comment by leecalcote** [comment]
Correct on both items, @ceterumnet. Much appreciated! 

Fixed in https://github.com/leecalcote/talks/commit/103832a9086ccad2037ae268567ddf8ef449d364
