### ISSUE TITLE
Broken link to 'Prometheus Storage 2.x and Remote Storage Adapters'

### ISSUE THREAD

**Issue by orhuidobro** [leecalcote/talks#4]
Link to [Prometheus Storage 2.x and Remote Storage Adapters](http://calcotestudios.com/talks/slides-scale-16x-using-prometheus-remote-storage-adapters.html) in https://www.socallinuxexpo.org/scale/16x/presentations/prometheus-storage-2x-and-remote-storage-adapters isn't working.

**Comment by leecalcote** [comment]
Thanks for reporting this, @orhuidobro! I've updated the link on the SCaLE site to point to http://calcotestudios.com/talks/decks/slides-scale-16x-using-prometheus-remote-storage-adapters.html.
